name: Wpm

on: 
  push:
    branches:
      - develop
      
jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3

        - name: Log in
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        - name: 'Log in to ACR'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.ACR_LOGIN_SERVER }}
            username: ${{ secrets.ACR_USERNAME }}
            password: ${{ secrets.ACR_PASSWORD }}
            
        - name: Set Date and Run Number
          id: set_date_run
          run: |
            # Get the current date in YYYY-MM-DD format
            CURRENT_DATE=$(date +'%Y-%m-%d')
            # Set the date and run number to environment variables
            echo "IMAGE_TAG=${CURRENT_DATE}-RN${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
            echo "CURRENT_DATE=${CURRENT_DATE}" >> $GITHUB_ENV
            echo "RUN_NUMBER=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

        - name: 'Building Wpm Management container image'
          run: |
              docker buildx build . -f Wpm.Managment.Api/Dockerfile -t ${{ secrets.ACR_LOGIN_SERVER }}/wpm-management-api:${{ env.IMAGE_TAG }}
        - name: 'Pushing Wpm Management container image'
          run: |
            docker push ${{ secrets.ACR_LOGIN_SERVER }}/wpm-management-api:${{ env.IMAGE_TAG }}
        
        - name: 'Building Wpm Clinic container image'
          run: |
            docker buildx build . -f Wpm.Clinic.Api/Dockerfile -t ${{ secrets.ACR_LOGIN_SERVER }}/wpm-clinic-api:${{ env.IMAGE_TAG }}
        - name: 'Pushing Wpm Clinic container image'
          run: |
            docker push ${{ secrets.ACR_LOGIN_SERVER }}/wpm-clinic-api:${{ env.IMAGE_TAG }}
            
        - name: 'Deploy to Wpm Management Container App'
          uses: azure/container-apps-deploy-action@v2
          with:
              acrName: ${{ secrets.ACR_USERNAME }}
              acrUsername: ${{ secrets.ACR_USERNAME }}
              acrPassword: ${{ secrets.ACR_PASSWORD }}
              containerAppName: wpm-management
              resourceGroup: wpm
              targetPort: 8080
              imageToDeploy: ${{ secrets.ACR_LOGIN_SERVER }}/wpm-management-api:${{ env.IMAGE_TAG }}
              environmentVariables: Logging__LogLevel__Microsoft.EntityFrameworkCore=Debug
              
        - name: 'Deploy to Wpm Management Container App'
          uses: azure/container-apps-deploy-action@v2
          with:
            acrName: ${{ secrets.ACR_USERNAME }}
            acrUsername: ${{ secrets.ACR_USERNAME }}
            acrPassword: ${{ secrets.ACR_PASSWORD }}
            containerAppName: wpm-clinic
            resourceGroup: wpm
            targetPort: 8081
            imageToDeploy: ${{ secrets.ACR_LOGIN_SERVER }}/wpm-clinic-api:${{ env.IMAGE_TAG }}
            environmentVariables: Logging__LogLevel__Microsoft.EntityFrameworkCore=Debug